### your site title here

title: Radovan Balog
description: Software Engineer | Lover of all things computer

baseurl: "" # the subpath of your site, e.g. /blog
url: https://radcho.github.io # the base hostname & protocol for your site, e.g. http://example.com
domain: radcho.github.io
email: radovanbalog@gmail.com

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
# twitter: "#"
linkedin: "radovan-balog-b02112101/"
# stackoverflow: "#"
github: "radcho"
# researchgate: "#"
# orcid: "#"
# quora: "#"
# instagram: "#"
# facebook: "#"


# Markdown
highlighter: rouge
markdown: kramdown

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
